# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81ffb487c6e50d855a8cebc99b75441d15b253d5e9c8497189b1ef47da7f0642fffd87038bc46de52a75bb97de342b184602e8a74ed267e3f5f9f4d73daea069

test:
  secret_key_base: f14868431ad3e54ae012cee6a6e10ec643cd6255b500035fec1a13474fd22a93069e541a1f450716b565a4d5791faa4401903b67b6c536dae82d302ffba6276c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
